### ISSUE TITLE
Crear actions de tareas

### ISSUE THREAD

**Issue by pausm99** [pausm99/pomos-garden#55]

**Comment by frmuller41182** [comment]
![Image](https://github.com/user-attachments/assets/30650a5b-23f6-4c3f-8fae-e06876acf2dc)

**Added first version of CRUD operations for Task Model**

NEXT STEPS

- Think about how we will add Tags and Sessions to Task model. The model only holds an array of strings, so the tag and session must be created before being added to the Task.
